
:cmock:
  :mock_prefix: mock_   
  :includes:
    - stubs.h
  :plugins:
    - :ignore
    - :ignore_arg
    - :callback
    - :expect
    - :expect_any_args
  :treat_as_array:
    discharge_config


    
